# Hugo configuration
baseURL: 'https://raghuwanshrajmishra.com/'
title: 'Raghuwansh Raj'
buildFuture: true
module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/v5
outputs:
  home:
    - HTML
    - RSS
    - JSON
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
security:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
